# Generated by Django 2.2.5 on 2019-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messagemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='conversation_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
